### ISSUE TITLE
Some gray box in the end of PDF

### ISSUE THREAD

**Issue by rbUUbr** [mileszs/wicked_pdf#669] opened 2017-07-11 16:59 UTC
Hi! I've got problem:
Always, after generate pdf, i get some gray box in the end of doc. Code:
```
respond_to do |format|
      format.html { render layout: 'briefs' }
      format.pdf do
        render pdf: "file_name_of_your_choice",
          template: "submitted_briefs/show_pdf.pdf.erb",
          layout: 'briefs',
          disable_javascript: true,
          locals: { submitted_brief: @submitted_brief }
      end
    end
```

![screenshot from 2017-07-11 19 57 36](https://user-images.githubusercontent.com/18901132/28080087-5e43e3da-6673-11e7-9b2f-f6871259e206.png)

**Comment by unixmonkey** [comment] 2017-07-11 17:21
That's almost certainly coming from your HTML or CSS, and not an issue with WickedPDF.

Try adding the `show_as_html: true` option to your `render` call and preview your PDF as an HTML page, and inspect to try and find what HTML/CSS could be causing that.

Closing this issue for now, but please update with your solution if you discover the cause and solution to potentially help others.

**Closed by unixmonkey** 2017-07-11 17:21 UTC
