### ISSUE TITLE
infinite loop for server when using WickedPdf?!

### ISSUE THREAD

**Issue by Argorate** [mileszs/wicked_pdf#672] opened 2017-07-28 10:07 UTC
I try use this method to create pdf : 

`pdf = WickedPdf.new.pdf_from_url('https://github.com/mileszs/wicked_pdf')`

but my rails server stay blocked. no log, no error, browser pending response in infinite loop...

don't understand what wrong...

**Comment by unixmonkey** [comment] 2017-07-28 16:19
I tried to reproduce your issue and wasn't quite able to.
Here's the relevant commit where I added this example to [the wicked_pdf_issues project](https://github.com/unixmonkey/wicked_pdf_issues/):
https://github.com/unixmonkey/wicked_pdf_issues/commit/03bf13669897f5804a2c13929dd4c9e5f004f8cd

However, this project's GitHub page takes quite a long time for wkhtmltopdf to process. On a machine bought this year, it takes me ~50 seconds to generate. It may take longer for you, but if you wait long enough, it *should* finish.

Because Heroku kills web requests that take too long, I changed out the wicked_pdf GitHub page for Google's homepage, since it loads and is processed much faster:
https://github.com/unixmonkey/wicked_pdf_issues/commit/9f53bb330103441201de01e68b3c71e5df2bd6ac

You can view the resulting pdf being generated on-the-fly here:
http://wicked-pdf-issues.herokuapp.com/pages/issue_672.pdf

There are other causes of a deadlock, like requesting other endpoints in your application like this:

```ruby
pdf = WickedPdf.new.pdf_from_url('https://myapp.com/other-endpoint')
```
Which can cause a single-threaded web server to deadlock because it must serve a second request when it hasn't finished your PDF request, resulting in a hung process.

That can be fixed by using a multithreaded rails server like [Puma](https://github.com/puma/puma) in development.

Let me know how it goes, or if you are having a different issue.
It might be helpful to provide more code, or at least what versions of Rails, wkhtmltopdf you are using.

Good luck! Let me know how it goes!

**Comment by Argorate** [comment] 2017-07-28 21:09
no, if I try the cmd in terminal it finish instantly. so I try use cmd line in ruby code directly but same loop happend...
for the moment i "slove" the problem with :

 ```
cmd       = "#{WickedPdf.config[:exe_path]} -q '#{url}' '#{file_path}'"

    begin
      Timeout::timeout(1) { system cmd }
    rescue
    end
```
the timeout force to finish, the pdf is generated fine... so if you have better solution I take ^^

I remove -q param, the rails server log tell me :

> Loading pages (1/6)
> [======>                                                     ] 10%

again : the same cmd directly in terminal was instantly done ;)

**Comment by Argorate** [comment] 2017-08-02 09:08
I use asset pipeline of rails with version of file concat to name file.
furthemore, I open window on destination path and I see the pdf file appear after the timeout...
so i don't think It's a cache problem.

Can we have log file to see what happen and if error is generate by wkhtmltopdf?

**Comment by unixmonkey** [comment] 2017-09-14 15:42
You can use `bundle open` and edit the gem to add `pry` breakpoints or `logger.info` wherever you like. You'll need to restart your app after editing the gems directly, and when you are done, you can run `bundle pristine` to re-download an unedited version of the gem.

You could also fork the gem and make edits in your fork, and install from your fork by changing the `Gemfile` to point to your version:

```ruby
# gem 'wicked_pdf'
gem 'wicked_pdf', github: 'argorate/wicked_pdf'
```

**Comment by Argorate** [comment] 2017-09-17 14:00
In fact, on my production serveur, I have no problem, but in local, I have to add Timeout ... inexplicable...

But that works in prod, its what I expect, thx.

**Closed** 2019-11-15 16:12 UTC
Labels: request-for-help
