### ISSUE TITLE
HTML not rendering properly

### ISSUE THREAD

**Issue by tgoldenberg** [mileszs/wicked_pdf#445] opened 2015-08-27 20:31 UTC
I switched over from wkhtmltopdf-binary to wkhtmltopdf-binary-edge as suggested in previous issue #344. This fixed my image rendering problem, but now certain words trigger a blank box in my HTML. One of the words is "workflow". If I remove the word from the p tag, the box goes away, but when I add it, the box is added to the end of the p tag. Weird!!! What should I do?!?

**Comment by garside** [comment] 2015-08-31 14:18
are you serious? what a ridiculous bug. -_-

**Comment by michaelachrisco** [comment] 2016-03-24 22:48
Can you give an example of this bug? I may have stumbled upon a fix (use a different font) but it may be related.

All I needed to do to fix this bug was add in something like:
```
table {border: 0; padding: 0; margin: 0 auto;font-family, Arial, sans-serif;font-size: 8px;}
```

**Comment by unixmonkey** [comment] 2016-03-25 02:55
Closing this as it doesn't appear to have anything to do with `wicked_pdf`, but feel free to continue discussion here. I hope you figure out what the difference is! It certainly sounds like it is related to fonts or font rendering. There is also a possibility that if you are running `wkhtmltopdf-binary-edge` on a non-Ubuntu linux system. The newer official builds of `wkhtmltopdf` aren't "fat" binaries, so you may have to build it yourself if you aren't using an Ubuntu-based system.

**Closed by unixmonkey** 2016-03-25 02:55 UTC
Labels: wkhtmltopdf

**Comment by michaelachrisco** [comment] 2016-03-27 17:39
@unixmonkey Funny thing is that I came across this gem and this issue from a composer package. Its reproducible in both wicked_pdf and snappy packages. The "box" I was getting was a char that was not rendering correctly because the font that I was using was buggy.

Ubuntu's default fonts were the issue. Pulling in a font like Font Awesome solved the issue in my case. 
Does `wkhtmltopdf-binary-edge` care about font directories or could one use a default within this repo?
