### ISSUE TITLE
undefined method `pathname' for nil:NilClass

### ISSUE THREAD

**Issue by fernandomm** [mileszs/wicked_pdf#375] opened 2015-01-06 01:23 UTC
Looks like that after ad81bec392884af337b6e16f001dfd9b8c50f2a7 you can't use this anymore:

```
<%= wicked_pdf_stylesheet_link_tag    "application", :media => "all" %>
```

It results in the following exception:

```
Exception: NoMethodError: undefined method `pathname' for nil:NilClass
--
0: /Users/fernando/.rvm/gems/ruby-2.1.3/bundler/gems/wicked_pdf-56aa1a195d65/lib/wicked_pdf/wicked_pdf_helper.rb:88:in `asset_pathname'
1: /Users/fernando/.rvm/gems/ruby-2.1.3/bundler/gems/wicked_pdf-56aa1a195d65/lib/wicked_pdf/wicked_pdf_helper.rb:67:in `wicked_pdf_asset_path'
2: /Users/fernando/.rvm/gems/ruby-2.1.3/bundler/gems/wicked_pdf-56aa1a195d65/lib/wicked_pdf/wicked_pdf_helper.rb:46:in `block in wicked_pdf_stylesheet_link_tag'
3: /Users/fernando/.rvm/gems/ruby-2.1.3/bundler/gems/wicked_pdf-56aa1a195d65/lib/wicked_pdf/wicked_pdf_helper.rb:45:in `gsub'
4: /Users/fernando/.rvm/gems/ruby-2.1.3/bundler/gems/wicked_pdf-56aa1a195d65/lib/wicked_pdf/wicked_pdf_helper.rb:45:in `wicked_pdf_stylesheet_link_tag'
```

With fbe435df09274f54e957b49de18da2e7894b9764 it works fine.

**Comment by fernandomm** [comment] 2015-01-06 10:07
Version 3.2.20

**Comment by unixmonkey** [comment] 2015-01-06 19:09
I think it is trying to do a regex against your stylesheet to replace `url()` calls with paths to local assets. Do you have any `url()`s in your stylesheets? Are they local or remote assets?

If you could paste a bit from your stylesheet where it first gets hung up, it would help me reproduce and debug.

**Comment by fernandomm** [comment] 2015-01-07 00:06
Yes, I have. It's in bootstrap.css. The following background-image definition is triggering this error:

```
[class*=" icon-"] {
  display: inline-block;
  width: 14px;
  height: 14px;
  margin-top: 1px;
  *margin-right: .3em;
  line-height: 14px;
  vertical-align: text-top;
  background-image: url("../img/glyphicons-halflings.png");
  background-position: 14px 14px;
  background-repeat: no-repeat;
}
```

**Comment by unixmonkey** [comment] 2015-01-07 18:03
Yep, that relative path isn't going to resolve to an asset through the pipeline, which is why `pathname` is failing :(

We could conditionally replace if the asset is found, and otherwise leave it alone. Do you think you could try contributing that?

**Comment by fernandomm** [comment] 2015-01-07 22:59
Did some tests here and it looks like before ad81bec the following line is not even called https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf/wicked_pdf_helper.rb#L88

Maybe changing from

```
Rails.application.assets.find_asset(source).pathname
```
to

```
Rails.application.assets.find_asset(source).try(:pathname)
```

is enough?

Unfortunately I'm not familiar with this project but with this change it produces the same result for my PDF as the previous version.

**Comment by abhishek77in** [comment] 2015-04-16 07:35
Dealing with the same issue (or similar issue). Will try to investigate and fix it myself.

**Comment by unixmonkey** [comment] 2015-04-16 14:00
`.try()` is part of Rails (not pure Ruby), so you could use `.send()` instead, but although this would prevent an exception being raised, that also means that this asset won't be loaded, but since the relative path looks to be to /public, and not from the asset pipeline, it wouldn't load anyway. I'm not big on silent failure, though. Other than parsing all stylesheets, I don't know what else to do. Maybe a `.send()` here is okay here.

**Comment by jhollinger** [comment] 2015-07-09 14:52
There's actually a problem with the regex itself. It eagerly matches `'"`, so instead of matching `path/to/asset.jpg` it matches `path/to/asset.jpg"); /* all the css */ url("other/asset.png`. And of course `find_asset` can't find an asset called `"path/to/asset.jpg\"); /* all the css */ url(\"other/asset.png"`. I've submitted a patch in PR #426.

**Comment by unixmonkey** [comment] 2015-07-09 14:57
Cool! Thanks for your help tracking it down!

I'm going to close this for now, if anyone has any issues, let me know here and I'll reopen.

**Closed by unixmonkey** 2015-07-09 14:57 UTC
Labels: asset-helpers

**Comment by brendon** [comment] 2015-09-22 02:31
I'm facing this problem with https://github.com/Semantic-Org/Semantic-UI-Rails-LESS

I was wondering @fernandomm could give me some tips on how he tracked down the offending `url()`?

**Comment by brendon** [comment] 2015-09-22 02:52
Ok, so I managed to find out it was balking on:

```
data:application/x-font-ttf;charset=utf-8;base64,AAEAAAALAIAAAwAwT1MvMggjB5AAAAC8AAAAYGNtYXAPfOIKAAABHAAAAExnYXNwAAAAEAAAAWgAAAAIZ2x5Zryj6HgAAAFwAAAAyGhlYWT/0IhHAAACOAAAADZoaGVhApkB5wAAAnAAAAAkaG10eAJuABIAAAKUAAAAGGxvY2EAjABWAAACrAAAAA5tYXhwAAgAFgAAArwAAAAgbmFtZfC1n04AAALcAAABPHBvc3QAAwAAAAAEGAAAACAAAwIAAZAABQAAAUwBZgAAAEcBTAFmAAAA9QAZAIQAAAAAAAAAAAAAAAAAAAABEAAAAAAAAAAAAAAAAAAAAABAAADw2gHg/+D/4AHgACAAAAABAAAAAAAAAAAAAAAgAAAAAAACAAAAAwAAABQAAwABAAAAFAAEADgAAAAKAAgAAgACAAEAIPDa//3//wAAAAAAIPDZ//3//wAB/+MPKwADAAEAAAAAAAAAAAAAAAEAAf//AA8AAQAAAAAAAAAAAAIAADc5AQAAAAABAAAAAAAAAAAAAgAANzkBAAAAAAEAAAAAAAAAAAACAAA3OQEAAAAAAQASAEkAtwFuABMAADc0PwE2FzYXFh0BFAcGJwYvASY1EgaABQgHBQYGBQcIBYAG2wcGfwcBAQcECf8IBAcBAQd/BgYAAAAAAQAAAEkApQFuABMAADcRNDc2MzIfARYVFA8BBiMiJyY1AAUGBwgFgAYGgAUIBwYFWwEACAUGBoAFCAcFgAYGBQcAAAABAAAAAQAAqWYls18PPPUACwIAAAAAAM/9o+4AAAAAz/2j7gAAAAAAtwFuAAAACAACAAAAAAAAAAEAAAHg/+AAAAIAAAAAAAC3AAEAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAQAAAAC3ABIAtwAAAAAAAAAKABQAHgBCAGQAAAABAAAABgAUAAEAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAADgCuAAEAAAAAAAEADAAAAAEAAAAAAAIADgBAAAEAAAAAAAMADAAiAAEAAAAAAAQADABOAAEAAAAAAAUAFgAMAAEAAAAAAAYABgAuAAEAAAAAAAoANABaAAMAAQQJAAEADAAAAAMAAQQJAAIADgBAAAMAAQQJAAMADAAiAAMAAQQJAAQADABOAAMAAQQJAAUAFgAMAAMAAQQJAAYADAA0AAMAAQQJAAoANABaAHIAYQB0AGkAbgBnAFYAZQByAHMAaQBvAG4AIAAxAC4AMAByAGEAdABpAG4AZ3JhdGluZwByAGEAdABpAG4AZwBSAGUAZwB1AGwAYQByAHIAYQB0AGkAbgBnAEYAbwBuAHQAIABnAGUAbgBlAHIAYQB0AGUAZAAgAGIAeQAgAEkAYwBvAE0AbwBvAG4ALgADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

so basically it's trying to find that in the asset pipeline.

**Comment by unixmonkey** [comment] 2015-09-22 13:36
@brendon,

@jhollinger fixed is issue by altering the regex [in this pull request](https://github.com/consolo/wicked_pdf/commit/11ec4b0bbe7f1a6a7fe21f8ccf692322a27e27cd).

This could be altered to ignore base64 encoded assets (maybe by ignoring if it starts with data:, or has base64 in it. Do you think you could help with that?

**Comment by brendon** [comment] 2015-09-23 01:19
Thanks @unixmonkey,

I didn't notice that regex initially and was focused on this one:

    URI_REGEXP = %r{^[-a-z]+://|^(?:cid|data):|^//}

I can probably help with this, but I came across another problem once I fixed (or bypassed) this issue. wicked_pdf (or probably rather wkhtmltopdf) is taking AGES (like 1-2 minutes) to create the PDF once the `semantic_ui` CSS is included.

Using the 'include all of the CSS inline' method that the tag helpers produce creates a huge amount of CPU activity while the PDF generates. I ended up solving that by using an absolute URL to the asset:

    = stylesheet_link_tag url_to_stylesheet('application'), media: 'all'

The CPU load is gone, but the generation time still takes forever. I'm going to do some research into wether it's a particular version of wkhtmltopdf that's causing this.

**Comment by fernandomm** [comment] 2015-09-23 02:20
Sorry for the late response. In order to find out which url() was failing i added a:

```
puts source
```

Before Rails.application.assets.find_asset(source).pathname. Not fancy, but it helped me to find out what was causing the problem.

**Comment by brendon** [comment] 2015-09-23 02:29
Thanks @fernandomm, I ended up doing something similar with logging to the log file. :)

**Comment by brendon** [comment] 2015-09-24 02:09
Oh boy! It's quite messy. I'm using Rails 4.2 and the logic of `asset_pathname` is completely wrong.

Say I have a `scss` file that has a `url()` reference in it that makes use of asset-path (e.g. `url(<%= asset_path 'blank.gif' %>)`). That gets compiled to be an absolute reference (from the root of the site) to that asset plus a fingerprint added to the end. `asset_pathname` is trying to rewrite that to be relative to `Rails.public_path` plus that rewritten asset path. Basically we end up with an incorrect path to the asset. In my case this asset is inside an engine in a gem so the real path isn't even inside Rails.root. Using `Rails.application.assets.find_asset 'blank'` finds it though. But it's too late to do that at this point because  of the appended fingerprint unless we want to manually strip that off (sounds brittle).

The only alternative I can think of is to override `asset-path` in `sass-rails` to make it aware of the wicked_pdf context. Or perhaps I'll look at what `asset-path` is calling inside Rails to see if that can be overridden instead. My semantic-ui gem uses less, so that would seem the smarter solution.

**Comment by brendon** [comment] 2015-09-25 02:21
Ok, I've come up with the following that works for me. Problem is, I'm not sure about previous versions of Rails, and I couldn't quite understand some of the code such as `precompiled_asset?`. I guess it's a starting point though:

```
    FINGERPRINT_REGEXP = /(-{1}[a-f0-9]{32}*\.{1}){1}/

    def asset_pathname(source)
      if source.start_with? '/assets/'
        source = source[8..-1] # Remove the /assets/ part
        source, fragment = source.split('#', 2) # Remove any fragments for now
        source, query = source.split('?', 2) # Remove any query parameters for now
        source = source.split('/')
        source.push(source.pop.gsub(FINGERPRINT_REGEXP, '.')) # Remove the fingerprint
        source = File.join(source)

        # We should now be able to find the asset. It's good to raise if we can't since
        # it's a problem the developer can correct by placing the missing file correctly.
        path = Rails.application.assets.find_asset(source).pathname.to_s
        path += '?' + query if query
        path += '#' + fragment if fragment

        path
      elsif (pathname = set_protocol(source)) =~ URI_REGEXP
        # Absolute URLs and data URLs are ok to just pass through unchanged
        pathname
      else
        # All others should be relative to the public directory
        Rails.public_path.join source.sub(/\A#{Rails.application.config.action_controller.relative_url_root}/, '')
      end
    end
```

**Comment by thiyagarajan** [comment] 2015-12-14 15:35
getting error

undefined method `start_with?' for nil:NilClass

 <%= wicked_pdf_stylesheet_link_tag 'application', :media => 'all' %>

**Comment by brendon** [comment] 2015-12-14 22:50
That means `nil` is being passed to `asset_pathname()` somewhere. It's probably from a url within the stylesheet. If there aren't many references to files in the stylesheet(s) try removing them one by one until the error goes away.

**Comment by franciscoGPS** [comment] 2016-01-14 18:05
Here I found very helpful info. I used a method posted by @unixmonkey and that really helped me out.
Thanks for your help. 
Here is part of my ***application_helper.erb***:

```ruby
 #https://github.com/mileszs/wicked_pdf/issues/275   <--- For more info
 
def asset_data_base64(path)
     asset = Rails.application.assets.find_asset(path)
     throw "Could not find asset '#{path}'" if asset.nil?
     base64 = Base64.encode64(asset.to_s).gsub(/\s+/, "")
     "data:#{asset.content_type};base64,#{Rack::Utils.escape(base64)}"
 end
```
And here is how my ***pdf.html.pdf*** ended up:
````
<head>
  <title>Factura</title>
  <%= stylesheet_link_tag(asset_data_base64('application.css')) %>
</head>
<div id="content">
````
Here is a link to the original issue, and the real explanation --> https://github.com/mileszs/wicked_pdf/issues/257
